# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2e02cc85de4d737999c1559c89ed9dc1"
name = "Algolia Sync Manual Sort"
handle = "algolia-sync-manual-sort"
application_url = "https://algolia-sync-manual-sort-still-frog-6279.fly.dev/"
embedded = true

[build]
automatically_update_urls_on_dev = false
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customer_events,read_files,read_inventory,read_metaobject_definitions,read_metaobjects,read_online_store_navigation,read_products,read_themes,write_files,write_inventory,write_metaobject_definitions,write_metaobjects,write_online_store_navigation,write_products,write_theme_code,write_themes"

[auth]
redirect_urls = [
  "https://algolia-sync-manual-sort-still-frog-6279.fly.dev/auth/callback",
  "https://algolia-sync-manual-sort-still-frog-6279.fly.dev/auth/shopify/callback",
  "https://algolia-sync-manual-sort-still-frog-6279.fly.dev/api/auth/callback"
]

[pos]
embedded = false
